## 중복 catch 블럭과 finally 구문

### `중복 catch 블럭 사용하기`

기본적으로 예외는 메서드 호출 시 발생하는 것이므로 사용하는 메서드들이 모두 서로 다른 예외 처리를 요구한다면 다음과 같이 코드가 작성될 수 있다.

```java
try {
    method1();
}
catch (AAAEception e) {
    ...
}

try {
    method2();
}
catch (BBBException e) {
    ...
}
```

그러나 이와 같이 작성하게 되면 매우 비효율적이므로 다음과 같이 try 블럭에 메서드들을 묶고 catch 블럭을 나열하는 방식을 주로 사용한다.

```java
try {
    method1();
    method2();
}
catch (AAAEception e) {
    ...
}
catch (BBBException e) {
    ...
}
```

만일 두개의 예외에 대해 동일한 처리를 한다고 가정하면 다음과 같이 예외들을 묶을 수 있다.

```java
catch (AAAException | BBBException e) {
    ...
}
```

이 경우에서 만일 두 예외가 부모 자식 관계라면 `부모 클래스` 만 명시해 주어야 한다.

혹은 여러 예외의 처리가 동일하다고 하면 그냥 최상위 클래스인 Exception 만 처리해도 같은 효과가 있다.

```java
catch(Exception e) {
    ...
}
```

### `예외처리 흐름과 처리 내용`

예외처리는 `try 블럭` 안에 있는 코드들이 차례로 실행되며 예외가 발생한 구문 이후의 코드들은 실행되지 않고 `catch 블럭` 에서 `해당 예외처리`를 따르게 된다. 앞의 예제에서 `method1()`에서 예외가 발생했다면 method2() 는 실행되지 않는다.

보통 예외 처리 블럭에서는 `예외 상황을 추적`하기 위해 `e.printStackTrace()` 메서드를 사용해 콘솔에 예외상황을 출력하여 문제를 해결하기 위한 도움 메시지로 활용하거나 좀 더 체계적으로 관리하기 위해서는 로거를 통해 로그를 남기는 형태로 구현하는 것이 좋다.

프로그램의 중요도나 상황에 따라 예외 발생 시 메모리 상의 데이터를 파일에 저장시킨다거나 새로운 데이터베이스로 연결을 전환하고 다시 시도한다거나 관리자에게 해당 상황을 알리는 코드 등으로 작성할 수 있다.

```java
catch(Exception e) {
    e.printStackTrace(e);
    ...
}
```

### `finally`

`finally` 는 예외가 발생한 경우나 혹은 발생하지 않은 경우 모두 수행되는 블럭을 지정할 때 사용한다. 코드의 `성공/실패 여부에 상관없이` 반드시 실행되어야 하는 구문들이 있다면 `finally`에 넣어줘야 한다.

```java
try {
    method1();
    method2();
}
catch (AAAEception e) {
    ...
}
catch (BBBException e) {
    ...
}
finally {
    ...
}
```

## 예외 던지기와 예외 클래스 작성

메서드를 만들 때 `throws` 구문을 넣어주면 현재 메서드에서 `특정 예외를 처리하지 않겠다` 는 의미가 된다. 이 말은 곧 해당 메서드를 호출하는 쪽에서 해당 예외 클래스에 대한 처리 즉 `try ~ catch` 블럭을 사용해야 한다는 것을 말한다.

이 방법은 메서드를 호출할 때 특정 특정 예외처리를 강제하도록 하는 데에도 사용되며 내가 만든 전용의 예외처리 클래스를 적용할 때도 적응이 된다.

```java
public void printData() throws IOException, MyException {

}
```

* printData() 메서드 안에서 IOException을 발생시키는 메서드를 사용할 경우 자체 처리를 하지 않고 호출하는 쪽으로 예외처리를 넘김
* 제공되는 예외클래스 이외에 내가 만든 예외 클래스 역시 throws 할 수 있음

직접 클래스를 만드는 경우 Exception 혹은 RuntimeException 클래스를 상속받아 구현하면 된다. 해당 예외는 예를 들면 앞의 printData() 메서드 내에서 특정 상황에 `throw MyException` 코드를 작성하시면서 예외 코드를 동작시킬 수 있다.

```java
public class MyException extends Exception {
    ...
}
```

## `사용자 예외 클래스 구현하기`

```java
public class MyException extends Exception {
    String exMsg;

    public MyException(String msg) {
        exMsg = "MyException: " + msg;
    }

    @Override
    public String getMessage() {
        return exMsg;
    }
}
```

- doException() 메서드에서 MyException 예외 클래스를 throws 처리 즉 호출하는쪽에서 예외처리 필요.
- num 변수값에 따라 OK 를 출력하거나 예외를 발생.
- main() 에서 인스턴스 생성후 doException() 메서드를 호출하고 `try~catch` 처리.

### 실행결과

```
com.dinfree.java.part1.MyException: MyException: doException
	at com.dinfree.java.part1.ExceptionTest2.doExeption(ExceptionTest2.java:10)
	at com.dinfree.java.part1.ExceptionTest2.main(ExceptionTest2.java:18)
```